language: node_js
node_js:
  - 10

services:
  - docker

before_install:
  - sudo apt-get update
  - npm i -g lerna @angular/cli

script:
  - docker-compose pull
  - lerna bootstrap
  - lerna exec --stream -- npm run build
  - lerna exec --stream -- npm run test

