language: node_js

node_js:
  - "10"

cache: npm

#services:
#  - docker

before_script:
#  - sudo apt-get update
  - npm i -g lerna @angular/cli
  - lerna bootstrap

script:
#  - docker-compose pull
  - lerna exec --stream -- npm run build
  - lerna exec --stream -- npm run test

