config:
  gcp:project: gotloop
  gcp:region: europe-west9
  gotloop:environment: production
  gotloop:domain: gotloop.io
  gotloop:cloudSqlTier: db-g1-small
  gotloop:minInstances: "0"
  gotloop:maxInstances: "10"
